[project]
name = "shared-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "XiantongC612", email = "xiantongc@knowwhy.tech" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
shared-template = "shared_template:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
